[package]
name = "dmalloc"
version = "0.0.1"
authors = ["Michael Egger <michael.egger@tsn.at>"]
edition = "2018"

[lib]
name = "dmalloc"
crate-type = ["dylib"]

[dependencies]
libc = "0.2"
libc-print = "0.1.11"
spin = "0.5.2"

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
opt-level = 1
debug = true
lto = true
debug-assertions = false
codegen-units = 16
overflow-checks = false